- merge-sort.py
> added merge sort function

- insertion_sort.py
> added insertion sort function

- bubble_sort.py
> added bubbleSort function

- selection_sort.py
> added selectionSort function

- Dijktra.py
Source taken from https://algocoding.wordpress.com/2015/03/28/dijkstras-algorithm-part-4a-python-implementation/
> Dijkstra’s Shortest Path Algorithm

- magicNumber.cpp
Referencing #11 
A number is said to be a magic number, if the sum of its digits are calculated till a single digit recursively by adding the sum of the digits after every addition. If the single digit comes out to be 1,then the number is a magic number.
> Added magic number code

- fibonacci.py
Algorithm for Fibonacci series
> Fibonacci algorithm

- HackerRank Problem/Java/MaximumPerimeterTriangle.java
The maximumPerimeterTriangle function returns an array of  integers that represent the side lengths of the chosen triangle in non-decreasing order.
maximumPerimeterTriangle has the following parameter(s):
sticks: an integer array that represents the lengths of sticks available
> [HackerRank] Maximum Perimeter Triangle

- HackerRank Problem/Python/SimpleArraySum.py
This solution implements the function simpleArraySum that receives an array (ar) and outputs the sum of the digits inside the array.
> [HackerRank] Simple Array Sum

- HackerRank Problem/Python/CompareTheTriplets.py
Added a file with Solution to the Compare the Triplets problem from HackerRank
> [HackerRank] Compare the Triplets

- HackerRank Problem/Python/MinMaxSum.py
This solution implements the function miniMaxSum(arr) that receives an array (arr) and outputs the max and the min of the sum of the values inside the array, except one, for each value.
> [HackerRank] Mini-Max Sum

- HackerRank Problem/C++/StoneDivisionRevisited.cpp
This is c++ solution to the "Stone Division, Revisited" problem in the Algorithm section of HackerRank.
> [HackerRank] Stone Division, Revisited

- HackerRank Problem/Ruby/Staircase.rb
> [HackerRank] Staircase

- HackerRank Problem/Python/Blacklist.py
> [HackerRank] The Blacklist

- HackerRank Problem/Python/PlusMinus.py
This solution implements the function plusMinus(arr) that receives an array (arr) and outputs the probability of a number being positive, negative or zero.
> [HackerRank] Plus Minus

- rightrotate.py
This is a python implementation to right rotate a list of n elements by k positions clockwise. The function rightRotate() returns the rotated list. The approach used in here is to traverse the elements in the first list one by one and then put the elements at required places in a second list.
> [Other]Right Rotate a list

- HackerRank Problem/Java/ConnectedCellsinaGrid.java
This is a Java8 solution to the "Connected Cells in a Grid" problem under the Algorithms section of HackerRank.
> [HackerRank] Connected Cells in a Grid

- HackerRank Problem/Python/FibonacciModified.py
Written code into a function name fibonacciModified and all the other code was by default by hackerrank.
Solution:
Written a recursive funtion call to get tn-2 and tn-1 to calculate tn=tn-2 + (tn-1)^2.
If in recursive function when we call t1 and t2 it returns 0 and 1 respectively(base condition).
> [HackerRank] Fibonacci Modified

- HackerRank Problem/Python/find a string.py
Print the number of times that the substring occurs in the given string.
> [HackerRank] Find a String

- HackerRank Problem/Python/FindTheRunnerUpScore.py
> [HackerRank] Find The RunnerUp Score

- HackerRank Problem/Java/ExtraLongFactorials.java
Java8 solution to the "Extra Long Factorials" problem under the Algorithms section of HackerRank. This solution includes 2 different solutions - recursive and non-recursive - for learning purposes.
>  [HackerRank] Extra Long Factorials

- HackerRank Problem/C++/BuildaPalindrome.cpp
This is a C++ solution to the "Build a Palindrome" problem in the Algorithm section of HackerRank.
> [HackerRank] Build a Palindrome

- HackerRank Problem/Python/Kangaroo.py
This is the Python solution of the Hackerrank problem [Kangaroo](https://www.hackerrank.com/challenges/kangaroo/problem) in the Algorithm section.
> [Hackerrank] Kangaroo

- HackerRank Problem/C++/RectangleArea.cpp
I have added a C++ program named RectangleArea.cpp that calculates the area of rectangle using concept of Inheritance.
> [HackerRank] Rectangle Area

- HackerRank Problem/C++/GameOfStones.cpp
> [HackerRank] Game of Stones

- HackerRank Problem/C++/TowerBreakers.cpp
> [HackerRank] Tower Breakers

- HackerRank Problem/Java/AVeryBigSum.java
Calculate and print the sum of the elements in an array, keeping in mind that some of those integers may be quite large.
> [HackerRank] AVeryBigSum

- HackerRank Problem/Python/SockMerchant.py
Added solution to SockMerchant problem in python
> [HackRank] Sock-Merchant

- HackerRank Problem/Python/TheTimeInWords.py
This solution implements the function timeInWords(h, m) that has two parameters, h for hour and m for minutes and it returns a time string.
> [HackerRank] The Time in Words

- HackerRank Problem/Python/DrawingBook.py
#28 
Solving Drawing Book using Python
> [HackerRank] Drawing Book

- HackerRank Problem/C/AngryProfessor.c
Angry Professor is an easy level algorithm problem available on the Hackerrank platform. The question can be solved with simple O(n) time complexity for loop and maintaining a running aggregate. 
Please follow the following link to see the entire Problem statement. 
Link: https://www.hackerrank.com/challenges/angry-professor/problem
> [HackerRank] Angry Professor

- HackerRank Problem/Java/NonDivisibleSubset.java
Given a set of distinct integers, print the size of a maximal subset of S where the sum of any 2 numbers in S′ is not evenly divisible by k.
For example, the array S=[19, 10, 12, 10, 24, 25, 22] and k=4. One of the arrays that can be created is S′[0]=[10, 12, 15]. Another is S′[1]=[19, 22, 24]. After testing all permutations, the maximum length solution array has 3 elements.
> [HackerRank] Non-Divisible Subset

- HackerRank Problem/Java/SimpleArraySum.java
- HackerRank Problem/Ruby/add_array_sum.rb
Function Description
Completed the simpleArraySum function. It returns the sum of the array elements as an integer.
simpleArraySum has the following parameter(s):
ar: an array of integers
Input Format
The first line contains an integer, , denoting the size of the array.
The second line contains  space-separated integers representing the array's elements.
> [HackerRank] Simple Array Sum Challenge # 1

- HackerRank Problem/Java/SimpleArraySum.java
- HackerRank Problem/Java/Solution.java
Calculate and print the sum of the elements in an array, keeping in mind that some of those integers may be quite large.
Function Description
Complete the aVeryBigSum function in the editor below. It must return the sum of all array elements.
aVeryBigSum has the following parameter(s):
ar: an array of integers .
Input Format
The first line of the input consists of an integer .
The next line contains  space-separated integers contained in the array.
Output Format
Print the integer sum of the elements in the array.
Constraints
Sample Input
5
1000000001 1000000002 1000000003 1000000004 1000000005
Output
5000000015
Note:
The range of the 32-bit integer is .
When we add several integer values, the resulting sum might exceed the above range. You might need to use long long int in C/C++ or long …
> [HackerRank] A Very Big Sum

- HackerRank Problem/Python/sequence_equation.py
…solution works by getting the index of a value, and then the index of that value.
> [HackerRank] Sequence Equation.

- HackerRank Problem/Python/MaximizeIt.py
This adds solution for "Maximize it!" problem from HackerRank
> [HackerRank] Maximize it!

- HackerRank Problem/Python/TimeConversion.py
This implements a solution to the "Time Conversion" problem on HackerRank.
> [HackerRank] Time Conversion in Python

- HackerRank Problem/C/CountingValleys.c
This implements a solution to the "counting valleys" problem on HackerRank.
> [HackerRank] Counting Valleys

- HackerRank Problem/Python/Encryption.py
This solution implements the function encryption(s), that receives a string s and returns a encrypted text.
#83
> [HackerRank] Encryption

- HackerRank Problem/Java/Staircase.java
The algorithm for solving the staircase problem in HackerRank
https://www.hackerrank.com/challenges/staircase/problem
> [HackerRank] Staircase.java

- HackerRank Problem/C/BonAppetit.c
This implements a solution to the ["Bon Appétit"](https://www.hackerrank.com/challenges/bon-appetit/problem) problem on HackerRank.
> [HackerRank] Bon Appétit in C

- HackerRank Problem/Python/DivisibleSumPairs.py
Find the number of pairs of numbers divisible by k in a list
#28
> [HackerRank] Divisible Sum Pairs

- HackerRank Problem/Java/HaloweenSale.java
> [HackerRank] Haloween Sale
